// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/service.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendType int32

const (
	BackendType_XRAY      BackendType = 0
	BackendType_WIREGUARD BackendType = 1
	BackendType_MTPROTO   BackendType = 2
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "XRAY",
		1: "WIREGUARD",
		2: "MTPROTO",
	}
	BackendType_value = map[string]int32{
		"XRAY":      0,
		"WIREGUARD": 1,
		"MTPROTO":   2,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_service_proto_enumTypes[0].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_common_service_proto_enumTypes[0]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{0}
}

type StatType int32

const (
	StatType_Outbounds StatType = 0
	StatType_Outbound  StatType = 1
	StatType_Inbounds  StatType = 2
	StatType_Inbound   StatType = 3
	StatType_UsersStat StatType = 4
	StatType_UserStat  StatType = 5
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "Outbounds",
		1: "Outbound",
		2: "Inbounds",
		3: "Inbound",
		4: "UsersStat",
		5: "UserStat",
	}
	StatType_value = map[string]int32{
		"Outbounds": 0,
		"Outbound":  1,
		"Inbounds":  2,
		"Inbound":   3,
		"UsersStat": 4,
		"UserStat":  5,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_service_proto_enumTypes[1].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_common_service_proto_enumTypes[1]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{0}
}

// Base info response message
type BaseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoResponse) Reset() {
	*x = BaseInfoResponse{}
	mi := &file_common_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoResponse) ProtoMessage() {}

func (x *BaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoResponse.ProtoReflect.Descriptor instead.
func (*BaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfoResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *BaseInfoResponse) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *BaseInfoResponse) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type Backend struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            BackendType            `protobuf:"varint,1,opt,name=type,proto3,enum=service.BackendType" json:"type,omitempty"`
	Config          string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Users           []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	KeepAlive       uint64                 `protobuf:"varint,4,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	ExcludeInbounds []string               `protobuf:"bytes,5,rep,name=exclude_inbounds,json=excludeInbounds,proto3" json:"exclude_inbounds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_common_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{2}
}

func (x *Backend) GetType() BackendType {
	if x != nil {
		return x.Type
	}
	return BackendType_XRAY
}

func (x *Backend) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Backend) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Backend) GetKeepAlive() uint64 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

func (x *Backend) GetExcludeInbounds() []string {
	if x != nil {
		return x.ExcludeInbounds
	}
	return nil
}

// log
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_common_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// stats
type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_common_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{4}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stat) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Stat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stat                `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_common_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{5}
}

func (x *StatResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	Type          StatType               `protobuf:"varint,3,opt,name=type,proto3,enum=service.StatType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_common_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{6}
}

func (x *StatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *StatRequest) GetType() StatType {
	if x != nil {
		return x.Type
	}
	return StatType_Outbounds
}

type OnlineStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineStatResponse) Reset() {
	*x = OnlineStatResponse{}
	mi := &file_common_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineStatResponse) ProtoMessage() {}

func (x *OnlineStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineStatResponse.ProtoReflect.Descriptor instead.
func (*OnlineStatResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineStatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OnlineStatResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatsOnlineIpListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           map[string]int64       `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsOnlineIpListResponse) Reset() {
	*x = StatsOnlineIpListResponse{}
	mi := &file_common_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsOnlineIpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsOnlineIpListResponse) ProtoMessage() {}

func (x *StatsOnlineIpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsOnlineIpListResponse.ProtoReflect.Descriptor instead.
func (*StatsOnlineIpListResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{8}
}

func (x *StatsOnlineIpListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatsOnlineIpListResponse) GetIps() map[string]int64 {
	if x != nil {
		return x.Ips
	}
	return nil
}

type BackendStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumGoroutine  uint32                 `protobuf:"varint,1,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	NumGc         uint32                 `protobuf:"varint,2,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	Alloc         uint64                 `protobuf:"varint,3,opt,name=alloc,proto3" json:"alloc,omitempty"`
	TotalAlloc    uint64                 `protobuf:"varint,4,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"`
	Sys           uint64                 `protobuf:"varint,5,opt,name=sys,proto3" json:"sys,omitempty"`
	Mallocs       uint64                 `protobuf:"varint,6,opt,name=mallocs,proto3" json:"mallocs,omitempty"`
	Frees         uint64                 `protobuf:"varint,7,opt,name=frees,proto3" json:"frees,omitempty"`
	LiveObjects   uint64                 `protobuf:"varint,8,opt,name=live_objects,json=liveObjects,proto3" json:"live_objects,omitempty"`
	PauseTotalNs  uint64                 `protobuf:"varint,9,opt,name=pause_total_ns,json=pauseTotalNs,proto3" json:"pause_total_ns,omitempty"`
	Uptime        uint32                 `protobuf:"varint,10,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendStatsResponse) Reset() {
	*x = BackendStatsResponse{}
	mi := &file_common_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendStatsResponse) ProtoMessage() {}

func (x *BackendStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendStatsResponse.ProtoReflect.Descriptor instead.
func (*BackendStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{9}
}

func (x *BackendStatsResponse) GetNumGoroutine() uint32 {
	if x != nil {
		return x.NumGoroutine
	}
	return 0
}

func (x *BackendStatsResponse) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *BackendStatsResponse) GetAlloc() uint64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *BackendStatsResponse) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *BackendStatsResponse) GetSys() uint64 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *BackendStatsResponse) GetMallocs() uint64 {
	if x != nil {
		return x.Mallocs
	}
	return 0
}

func (x *BackendStatsResponse) GetFrees() uint64 {
	if x != nil {
		return x.Frees
	}
	return 0
}

func (x *BackendStatsResponse) GetLiveObjects() uint64 {
	if x != nil {
		return x.LiveObjects
	}
	return 0
}

func (x *BackendStatsResponse) GetPauseTotalNs() uint64 {
	if x != nil {
		return x.PauseTotalNs
	}
	return 0
}

func (x *BackendStatsResponse) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type SystemStatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MemTotal               uint64                 `protobuf:"varint,1,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed                uint64                 `protobuf:"varint,2,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	CpuCores               uint64                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsage               float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	IncomingBandwidthSpeed uint64                 `protobuf:"varint,5,opt,name=incoming_bandwidth_speed,json=incomingBandwidthSpeed,proto3" json:"incoming_bandwidth_speed,omitempty"`
	OutgoingBandwidthSpeed uint64                 `protobuf:"varint,6,opt,name=outgoing_bandwidth_speed,json=outgoingBandwidthSpeed,proto3" json:"outgoing_bandwidth_speed,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_common_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{10}
}

func (x *SystemStatsResponse) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemStatsResponse) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemStatsResponse) GetIncomingBandwidthSpeed() uint64 {
	if x != nil {
		return x.IncomingBandwidthSpeed
	}
	return 0
}

func (x *SystemStatsResponse) GetOutgoingBandwidthSpeed() uint64 {
	if x != nil {
		return x.OutgoingBandwidthSpeed
	}
	return 0
}

// User
type Vmess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vmess) Reset() {
	*x = Vmess{}
	mi := &file_common_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vmess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vmess) ProtoMessage() {}

func (x *Vmess) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vmess.ProtoReflect.Descriptor instead.
func (*Vmess) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{11}
}

func (x *Vmess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Vless struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vless) Reset() {
	*x = Vless{}
	mi := &file_common_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vless) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vless) ProtoMessage() {}

func (x *Vless) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vless.ProtoReflect.Descriptor instead.
func (*Vless) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{12}
}

func (x *Vless) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vless) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

type Trojan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trojan) Reset() {
	*x = Trojan{}
	mi := &file_common_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trojan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trojan) ProtoMessage() {}

func (x *Trojan) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trojan.ProtoReflect.Descriptor instead.
func (*Trojan) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{13}
}

func (x *Trojan) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Shadowsocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shadowsocks) Reset() {
	*x = Shadowsocks{}
	mi := &file_common_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shadowsocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shadowsocks) ProtoMessage() {}

func (x *Shadowsocks) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shadowsocks.ProtoReflect.Descriptor instead.
func (*Shadowsocks) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{14}
}

func (x *Shadowsocks) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Shadowsocks) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Wireguard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PeerIps       []string               `protobuf:"bytes,2,rep,name=peer_ips,json=peerIps,proto3" json:"peer_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wireguard) Reset() {
	*x = Wireguard{}
	mi := &file_common_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wireguard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wireguard) ProtoMessage() {}

func (x *Wireguard) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wireguard.ProtoReflect.Descriptor instead.
func (*Wireguard) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{15}
}

func (x *Wireguard) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Wireguard) GetPeerIps() []string {
	if x != nil {
		return x.PeerIps
	}
	return nil
}

type Hysteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hysteria) Reset() {
	*x = Hysteria{}
	mi := &file_common_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hysteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hysteria) ProtoMessage() {}

func (x *Hysteria) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hysteria.ProtoReflect.Descriptor instead.
func (*Hysteria) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{16}
}

func (x *Hysteria) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type Mtproto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Secret            string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	UserAdTag         string                 `protobuf:"bytes,2,opt,name=user_ad_tag,json=userAdTag,proto3" json:"user_ad_tag,omitempty"`
	MaxTcpConns       uint32                 `protobuf:"varint,3,opt,name=max_tcp_conns,json=maxTcpConns,proto3" json:"max_tcp_conns,omitempty"`
	ExpirationRfc3339 string                 `protobuf:"bytes,4,opt,name=expiration_rfc3339,json=expirationRfc3339,proto3" json:"expiration_rfc3339,omitempty"`
	DataQuotaBytes    uint64                 `protobuf:"varint,5,opt,name=data_quota_bytes,json=dataQuotaBytes,proto3" json:"data_quota_bytes,omitempty"`
	MaxUniqueIps      uint32                 `protobuf:"varint,6,opt,name=max_unique_ips,json=maxUniqueIps,proto3" json:"max_unique_ips,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Mtproto) Reset() {
	*x = Mtproto{}
	mi := &file_common_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mtproto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mtproto) ProtoMessage() {}

func (x *Mtproto) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mtproto.ProtoReflect.Descriptor instead.
func (*Mtproto) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{17}
}

func (x *Mtproto) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Mtproto) GetUserAdTag() string {
	if x != nil {
		return x.UserAdTag
	}
	return ""
}

func (x *Mtproto) GetMaxTcpConns() uint32 {
	if x != nil {
		return x.MaxTcpConns
	}
	return 0
}

func (x *Mtproto) GetExpirationRfc3339() string {
	if x != nil {
		return x.ExpirationRfc3339
	}
	return ""
}

func (x *Mtproto) GetDataQuotaBytes() uint64 {
	if x != nil {
		return x.DataQuotaBytes
	}
	return 0
}

func (x *Mtproto) GetMaxUniqueIps() uint32 {
	if x != nil {
		return x.MaxUniqueIps
	}
	return 0
}

type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vmess         *Vmess                 `protobuf:"bytes,1,opt,name=vmess,proto3" json:"vmess,omitempty"`
	Vless         *Vless                 `protobuf:"bytes,2,opt,name=vless,proto3" json:"vless,omitempty"`
	Trojan        *Trojan                `protobuf:"bytes,3,opt,name=trojan,proto3" json:"trojan,omitempty"`
	Shadowsocks   *Shadowsocks           `protobuf:"bytes,4,opt,name=shadowsocks,proto3" json:"shadowsocks,omitempty"`
	Wireguard     *Wireguard             `protobuf:"bytes,5,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	Hysteria      *Hysteria              `protobuf:"bytes,6,opt,name=hysteria,proto3" json:"hysteria,omitempty"`
	Mtproto       *Mtproto               `protobuf:"bytes,7,opt,name=mtproto,proto3" json:"mtproto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_common_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{18}
}

func (x *Proxy) GetVmess() *Vmess {
	if x != nil {
		return x.Vmess
	}
	return nil
}

func (x *Proxy) GetVless() *Vless {
	if x != nil {
		return x.Vless
	}
	return nil
}

func (x *Proxy) GetTrojan() *Trojan {
	if x != nil {
		return x.Trojan
	}
	return nil
}

func (x *Proxy) GetShadowsocks() *Shadowsocks {
	if x != nil {
		return x.Shadowsocks
	}
	return nil
}

func (x *Proxy) GetWireguard() *Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

func (x *Proxy) GetHysteria() *Hysteria {
	if x != nil {
		return x.Hysteria
	}
	return nil
}

func (x *Proxy) GetMtproto() *Mtproto {
	if x != nil {
		return x.Mtproto
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Proxies       *Proxy                 `protobuf:"bytes,2,opt,name=proxies,proto3" json:"proxies,omitempty"`
	Inbounds      []string               `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetProxies() *Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *User) GetInbounds() []string {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_common_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{20}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UsersChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersChunk) Reset() {
	*x = UsersChunk{}
	mi := &file_common_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersChunk) ProtoMessage() {}

func (x *UsersChunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersChunk.ProtoReflect.Descriptor instead.
func (*UsersChunk) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{21}
}

func (x *UsersChunk) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UsersChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

var File_common_service_proto protoreflect.FileDescriptor

const file_common_service_proto_rawDesc = "" +
	"\n" +
	"\x14common/service.proto\x12\aservice\"\a\n" +
	"\x05Empty\"r\n" +
	"\x10BaseInfoResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12!\n" +
	"\fnode_version\x18\x03 \x01(\tR\vnodeVersion\"\xba\x01\n" +
	"\aBackend\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.service.BackendTypeR\x04type\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12#\n" +
	"\x05users\x18\x03 \x03(\v2\r.service.UserR\x05users\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x04 \x01(\x04R\tkeepAlive\x12)\n" +
	"\x10exclude_inbounds\x18\x05 \x03(\tR\x0fexcludeInbounds\"\x1d\n" +
	"\x03Log\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detail\"X\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\"3\n" +
	"\fStatResponse\x12#\n" +
	"\x05stats\x18\x01 \x03(\v2\r.service.StatR\x05stats\"^\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.service.StatTypeR\x04type\">\n" +
	"\x12OnlineStatResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xa6\x01\n" +
	"\x19StatsOnlineIpListResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x03ips\x18\x02 \x03(\v2+.service.StatsOnlineIpListResponse.IpsEntryR\x03ips\x1a6\n" +
	"\bIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xac\x02\n" +
	"\x14BackendStatsResponse\x12#\n" +
	"\rnum_goroutine\x18\x01 \x01(\rR\fnumGoroutine\x12\x15\n" +
	"\x06num_gc\x18\x02 \x01(\rR\x05numGc\x12\x14\n" +
	"\x05alloc\x18\x03 \x01(\x04R\x05alloc\x12\x1f\n" +
	"\vtotal_alloc\x18\x04 \x01(\x04R\n" +
	"totalAlloc\x12\x10\n" +
	"\x03sys\x18\x05 \x01(\x04R\x03sys\x12\x18\n" +
	"\amallocs\x18\x06 \x01(\x04R\amallocs\x12\x14\n" +
	"\x05frees\x18\a \x01(\x04R\x05frees\x12!\n" +
	"\flive_objects\x18\b \x01(\x04R\vliveObjects\x12$\n" +
	"\x0epause_total_ns\x18\t \x01(\x04R\fpauseTotalNs\x12\x16\n" +
	"\x06uptime\x18\n" +
	" \x01(\rR\x06uptime\"\xfb\x01\n" +
	"\x13SystemStatsResponse\x12\x1b\n" +
	"\tmem_total\x18\x01 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x02 \x01(\x04R\amemUsed\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x04R\bcpuCores\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x128\n" +
	"\x18incoming_bandwidth_speed\x18\x05 \x01(\x04R\x16incomingBandwidthSpeed\x128\n" +
	"\x18outgoing_bandwidth_speed\x18\x06 \x01(\x04R\x16outgoingBandwidthSpeed\"\x17\n" +
	"\x05Vmess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x05Vless\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\"$\n" +
	"\x06Trojan\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"A\n" +
	"\vShadowsocks\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"E\n" +
	"\tWireguard\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x19\n" +
	"\bpeer_ips\x18\x02 \x03(\tR\apeerIps\"\x1e\n" +
	"\bHysteria\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\"\xe4\x01\n" +
	"\aMtproto\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1e\n" +
	"\vuser_ad_tag\x18\x02 \x01(\tR\tuserAdTag\x12\"\n" +
	"\rmax_tcp_conns\x18\x03 \x01(\rR\vmaxTcpConns\x12-\n" +
	"\x12expiration_rfc3339\x18\x04 \x01(\tR\x11expirationRfc3339\x12(\n" +
	"\x10data_quota_bytes\x18\x05 \x01(\x04R\x0edataQuotaBytes\x12$\n" +
	"\x0emax_unique_ips\x18\x06 \x01(\rR\fmaxUniqueIps\"\xc1\x02\n" +
	"\x05Proxy\x12$\n" +
	"\x05vmess\x18\x01 \x01(\v2\x0e.service.VmessR\x05vmess\x12$\n" +
	"\x05vless\x18\x02 \x01(\v2\x0e.service.VlessR\x05vless\x12'\n" +
	"\x06trojan\x18\x03 \x01(\v2\x0f.service.TrojanR\x06trojan\x126\n" +
	"\vshadowsocks\x18\x04 \x01(\v2\x14.service.ShadowsocksR\vshadowsocks\x120\n" +
	"\twireguard\x18\x05 \x01(\v2\x12.service.WireguardR\twireguard\x12-\n" +
	"\bhysteria\x18\x06 \x01(\v2\x11.service.HysteriaR\bhysteria\x12*\n" +
	"\amtproto\x18\a \x01(\v2\x10.service.MtprotoR\amtproto\"b\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12(\n" +
	"\aproxies\x18\x02 \x01(\v2\x0e.service.ProxyR\aproxies\x12\x1a\n" +
	"\binbounds\x18\x03 \x03(\tR\binbounds\",\n" +
	"\x05Users\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.service.UserR\x05users\"[\n" +
	"\n" +
	"UsersChunk\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.service.UserR\x05users\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last*3\n" +
	"\vBackendType\x12\b\n" +
	"\x04XRAY\x10\x00\x12\r\n" +
	"\tWIREGUARD\x10\x01\x12\v\n" +
	"\aMTPROTO\x10\x02*_\n" +
	"\bStatType\x12\r\n" +
	"\tOutbounds\x10\x00\x12\f\n" +
	"\bOutbound\x10\x01\x12\f\n" +
	"\bInbounds\x10\x02\x12\v\n" +
	"\aInbound\x10\x03\x12\r\n" +
	"\tUsersStat\x10\x04\x12\f\n" +
	"\bUserStat\x10\x052\xd7\x05\n" +
	"\vNodeService\x126\n" +
	"\x05Start\x12\x10.service.Backend\x1a\x19.service.BaseInfoResponse\"\x00\x12(\n" +
	"\x04Stop\x12\x0e.service.Empty\x1a\x0e.service.Empty\"\x00\x12:\n" +
	"\vGetBaseInfo\x12\x0e.service.Empty\x1a\x19.service.BaseInfoResponse\"\x00\x12+\n" +
	"\aGetLogs\x12\x0e.service.Empty\x1a\f.service.Log\"\x000\x01\x12@\n" +
	"\x0eGetSystemStats\x12\x0e.service.Empty\x1a\x1c.service.SystemStatsResponse\"\x00\x12B\n" +
	"\x0fGetBackendStats\x12\x0e.service.Empty\x1a\x1d.service.BackendStatsResponse\"\x00\x129\n" +
	"\bGetStats\x12\x14.service.StatRequest\x1a\x15.service.StatResponse\"\x00\x12I\n" +
	"\x12GetUserOnlineStats\x12\x14.service.StatRequest\x1a\x1b.service.OnlineStatResponse\"\x00\x12V\n" +
	"\x18GetUserOnlineIpListStats\x12\x14.service.StatRequest\x1a\".service.StatsOnlineIpListResponse\"\x00\x12-\n" +
	"\bSyncUser\x12\r.service.User\x1a\x0e.service.Empty\"\x00(\x01\x12-\n" +
	"\tSyncUsers\x12\x0e.service.Users\x1a\x0e.service.Empty\"\x00\x12;\n" +
	"\x10SyncUsersChunked\x12\x13.service.UsersChunk\x1a\x0e.service.Empty\"\x00(\x01B#Z!github.com/pasarguard/node/commonb\x06proto3"

var (
	file_common_service_proto_rawDescOnce sync.Once
	file_common_service_proto_rawDescData []byte
)

func file_common_service_proto_rawDescGZIP() []byte {
	file_common_service_proto_rawDescOnce.Do(func() {
		file_common_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_service_proto_rawDesc), len(file_common_service_proto_rawDesc)))
	})
	return file_common_service_proto_rawDescData
}

var file_common_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_common_service_proto_goTypes = []any{
	(BackendType)(0),                  // 0: service.BackendType
	(StatType)(0),                     // 1: service.StatType
	(*Empty)(nil),                     // 2: service.Empty
	(*BaseInfoResponse)(nil),          // 3: service.BaseInfoResponse
	(*Backend)(nil),                   // 4: service.Backend
	(*Log)(nil),                       // 5: service.Log
	(*Stat)(nil),                      // 6: service.Stat
	(*StatResponse)(nil),              // 7: service.StatResponse
	(*StatRequest)(nil),               // 8: service.StatRequest
	(*OnlineStatResponse)(nil),        // 9: service.OnlineStatResponse
	(*StatsOnlineIpListResponse)(nil), // 10: service.StatsOnlineIpListResponse
	(*BackendStatsResponse)(nil),      // 11: service.BackendStatsResponse
	(*SystemStatsResponse)(nil),       // 12: service.SystemStatsResponse
	(*Vmess)(nil),                     // 13: service.Vmess
	(*Vless)(nil),                     // 14: service.Vless
	(*Trojan)(nil),                    // 15: service.Trojan
	(*Shadowsocks)(nil),               // 16: service.Shadowsocks
	(*Wireguard)(nil),                 // 17: service.Wireguard
	(*Hysteria)(nil),                  // 18: service.Hysteria
	(*Mtproto)(nil),                   // 19: service.Mtproto
	(*Proxy)(nil),                     // 20: service.Proxy
	(*User)(nil),                      // 21: service.User
	(*Users)(nil),                     // 22: service.Users
	(*UsersChunk)(nil),                // 23: service.UsersChunk
	nil,                               // 24: service.StatsOnlineIpListResponse.IpsEntry
}
var file_common_service_proto_depIdxs = []int32{
	0,  // 0: service.Backend.type:type_name -> service.BackendType
	21, // 1: service.Backend.users:type_name -> service.User
	6,  // 2: service.StatResponse.stats:type_name -> service.Stat
	1,  // 3: service.StatRequest.type:type_name -> service.StatType
	24, // 4: service.StatsOnlineIpListResponse.ips:type_name -> service.StatsOnlineIpListResponse.IpsEntry
	13, // 5: service.Proxy.vmess:type_name -> service.Vmess
	14, // 6: service.Proxy.vless:type_name -> service.Vless
	15, // 7: service.Proxy.trojan:type_name -> service.Trojan
	16, // 8: service.Proxy.shadowsocks:type_name -> service.Shadowsocks
	17, // 9: service.Proxy.wireguard:type_name -> service.Wireguard
	18, // 10: service.Proxy.hysteria:type_name -> service.Hysteria
	19, // 11: service.Proxy.mtproto:type_name -> service.Mtproto
	20, // 12: service.User.proxies:type_name -> service.Proxy
	21, // 13: service.Users.users:type_name -> service.User
	21, // 14: service.UsersChunk.users:type_name -> service.User
	4,  // 15: service.NodeService.Start:input_type -> service.Backend
	2,  // 16: service.NodeService.Stop:input_type -> service.Empty
	2,  // 17: service.NodeService.GetBaseInfo:input_type -> service.Empty
	2,  // 18: service.NodeService.GetLogs:input_type -> service.Empty
	2,  // 19: service.NodeService.GetSystemStats:input_type -> service.Empty
	2,  // 20: service.NodeService.GetBackendStats:input_type -> service.Empty
	8,  // 21: service.NodeService.GetStats:input_type -> service.StatRequest
	8,  // 22: service.NodeService.GetUserOnlineStats:input_type -> service.StatRequest
	8,  // 23: service.NodeService.GetUserOnlineIpListStats:input_type -> service.StatRequest
	21, // 24: service.NodeService.SyncUser:input_type -> service.User
	22, // 25: service.NodeService.SyncUsers:input_type -> service.Users
	23, // 26: service.NodeService.SyncUsersChunked:input_type -> service.UsersChunk
	3,  // 27: service.NodeService.Start:output_type -> service.BaseInfoResponse
	2,  // 28: service.NodeService.Stop:output_type -> service.Empty
	3,  // 29: service.NodeService.GetBaseInfo:output_type -> service.BaseInfoResponse
	5,  // 30: service.NodeService.GetLogs:output_type -> service.Log
	12, // 31: service.NodeService.GetSystemStats:output_type -> service.SystemStatsResponse
	11, // 32: service.NodeService.GetBackendStats:output_type -> service.BackendStatsResponse
	7,  // 33: service.NodeService.GetStats:output_type -> service.StatResponse
	9,  // 34: service.NodeService.GetUserOnlineStats:output_type -> service.OnlineStatResponse
	10, // 35: service.NodeService.GetUserOnlineIpListStats:output_type -> service.StatsOnlineIpListResponse
	2,  // 36: service.NodeService.SyncUser:output_type -> service.Empty
	2,  // 37: service.NodeService.SyncUsers:output_type -> service.Empty
	2,  // 38: service.NodeService.SyncUsersChunked:output_type -> service.Empty
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_common_service_proto_init() }
func file_common_service_proto_init() {
	if File_common_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_service_proto_rawDesc), len(file_common_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_service_proto_goTypes,
		DependencyIndexes: file_common_service_proto_depIdxs,
		EnumInfos:         file_common_service_proto_enumTypes,
		MessageInfos:      file_common_service_proto_msgTypes,
	}.Build()
	File_common_service_proto = out.File
	file_common_service_proto_goTypes = nil
	file_common_service_proto_depIdxs = nil
}
